class SurahInfo {
  final int number;
  final String nameArabic;
  final String nameTranslit;
  final String nameRussian;
  final String nameEnglish;
  final int ayahCount;
  final bool isMeccan;

  const SurahInfo({
    required this.number,
    required this.nameArabic,
    required this.nameTranslit,
    required this.nameRussian,
    required this.nameEnglish,
    required this.ayahCount,
    required this.isMeccan,
  });
}

const List<SurahInfo> kSurahs = [
  SurahInfo(number: 1, nameArabic: 'الفاتحة', nameTranslit: 'Al-Fatihah', nameRussian: 'Открывающая', nameEnglish: 'The Opening', ayahCount: 7, isMeccan: true),
  SurahInfo(number: 2, nameArabic: 'البقرة', nameTranslit: 'Al-Baqarah', nameRussian: 'Корова', nameEnglish: 'The Cow', ayahCount: 286, isMeccan: false),
  SurahInfo(number: 3, nameArabic: 'آل عمران', nameTranslit: 'Aali Imran', nameRussian: 'Семейство Имрана', nameEnglish: 'Family of Imran', ayahCount: 200, isMeccan: false),
  SurahInfo(number: 4, nameArabic: 'النساء', nameTranslit: 'An-Nisa', nameRussian: 'Женщины', nameEnglish: 'The Women', ayahCount: 176, isMeccan: false),
  SurahInfo(number: 5, nameArabic: 'المائدة', nameTranslit: 'Al-Maidah', nameRussian: 'Трапеза', nameEnglish: 'The Table Spread', ayahCount: 120, isMeccan: false),
  SurahInfo(number: 6, nameArabic: 'الأنعام', nameTranslit: 'Al-Anam', nameRussian: 'Скот', nameEnglish: 'The Cattle', ayahCount: 165, isMeccan: true),
  SurahInfo(number: 7, nameArabic: 'الأعراف', nameTranslit: 'Al-Araf', nameRussian: 'Преграды', nameEnglish: 'The Heights', ayahCount: 206, isMeccan: true),
  SurahInfo(number: 8, nameArabic: 'الأنفال', nameTranslit: 'Al-Anfal', nameRussian: 'Трофеи', nameEnglish: 'The Spoils of War', ayahCount: 75, isMeccan: false),
  SurahInfo(number: 9, nameArabic: 'التوبة', nameTranslit: 'At-Tawbah', nameRussian: 'Покаяние', nameEnglish: 'The Repentance', ayahCount: 129, isMeccan: false),
  SurahInfo(number: 10, nameArabic: 'يونس', nameTranslit: 'Yunus', nameRussian: 'Йунус', nameEnglish: 'Jonah', ayahCount: 109, isMeccan: true),
  SurahInfo(number: 11, nameArabic: 'هود', nameTranslit: 'Hud', nameRussian: 'Худ', nameEnglish: 'Hud', ayahCount: 123, isMeccan: true),
  SurahInfo(number: 12, nameArabic: 'يوسف', nameTranslit: 'Yusuf', nameRussian: 'Йусуф', nameEnglish: 'Joseph', ayahCount: 111, isMeccan: true),
  SurahInfo(number: 13, nameArabic: 'الرعد', nameTranslit: 'Ar-Rad', nameRussian: 'Гром', nameEnglish: 'The Thunder', ayahCount: 43, isMeccan: false),
  SurahInfo(number: 14, nameArabic: 'إبراهيم', nameTranslit: 'Ibrahim', nameRussian: 'Ибрахим', nameEnglish: 'Abraham', ayahCount: 52, isMeccan: true),
  SurahInfo(number: 15, nameArabic: 'الحجر', nameTranslit: 'Al-Hijr', nameRussian: 'Хиджр', nameEnglish: 'The Rocky Tract', ayahCount: 99, isMeccan: true),
  SurahInfo(number: 16, nameArabic: 'النحل', nameTranslit: 'An-Nahl', nameRussian: 'Пчёлы', nameEnglish: 'The Bee', ayahCount: 128, isMeccan: true),
  SurahInfo(number: 17, nameArabic: 'الإسراء', nameTranslit: 'Al-Isra', nameRussian: 'Ночной перенос', nameEnglish: 'The Night Journey', ayahCount: 111, isMeccan: true),
  SurahInfo(number: 18, nameArabic: 'الكهف', nameTranslit: 'Al-Kahf', nameRussian: 'Пещера', nameEnglish: 'The Cave', ayahCount: 110, isMeccan: true),
  SurahInfo(number: 19, nameArabic: 'مريم', nameTranslit: 'Maryam', nameRussian: 'Марьям', nameEnglish: 'Mary', ayahCount: 98, isMeccan: true),
  SurahInfo(number: 20, nameArabic: 'طه', nameTranslit: 'Ta-Ha', nameRussian: 'Та Ха', nameEnglish: 'Ta-Ha', ayahCount: 135, isMeccan: true),
  SurahInfo(number: 21, nameArabic: 'الأنبياء', nameTranslit: 'Al-Anbiya', nameRussian: 'Пророки', nameEnglish: 'The Prophets', ayahCount: 112, isMeccan: true),
  SurahInfo(number: 22, nameArabic: 'الحج', nameTranslit: 'Al-Hajj', nameRussian: 'Хадж', nameEnglish: 'The Pilgrimage', ayahCount: 78, isMeccan: false),
  SurahInfo(number: 23, nameArabic: 'المؤمنون', nameTranslit: 'Al-Muminun', nameRussian: 'Верующие', nameEnglish: 'The Believers', ayahCount: 118, isMeccan: true),
  SurahInfo(number: 24, nameArabic: 'النور', nameTranslit: 'An-Nur', nameRussian: 'Свет', nameEnglish: 'The Light', ayahCount: 64, isMeccan: false),
  SurahInfo(number: 25, nameArabic: 'الفرقان', nameTranslit: 'Al-Furqan', nameRussian: 'Различение', nameEnglish: 'The Criterion', ayahCount: 77, isMeccan: true),
  SurahInfo(number: 26, nameArabic: 'الشعراء', nameTranslit: 'Ash-Shuara', nameRussian: 'Поэты', nameEnglish: 'The Poets', ayahCount: 227, isMeccan: true),
  SurahInfo(number: 27, nameArabic: 'النمل', nameTranslit: 'An-Naml', nameRussian: 'Муравьи', nameEnglish: 'The Ant', ayahCount: 93, isMeccan: true),
  SurahInfo(number: 28, nameArabic: 'القصص', nameTranslit: 'Al-Qasas', nameRussian: 'Рассказ', nameEnglish: 'The Stories', ayahCount: 88, isMeccan: true),
  SurahInfo(number: 29, nameArabic: 'العنكبوت', nameTranslit: 'Al-Ankabut', nameRussian: 'Паук', nameEnglish: 'The Spider', ayahCount: 69, isMeccan: true),
  SurahInfo(number: 30, nameArabic: 'الروم', nameTranslit: 'Ar-Rum', nameRussian: 'Римляне', nameEnglish: 'The Romans', ayahCount: 60, isMeccan: true),
  SurahInfo(number: 31, nameArabic: 'لقمان', nameTranslit: 'Luqman', nameRussian: 'Лукман', nameEnglish: 'Luqman', ayahCount: 34, isMeccan: true),
  SurahInfo(number: 32, nameArabic: 'السجدة', nameTranslit: 'As-Sajdah', nameRussian: 'Поклон', nameEnglish: 'The Prostration', ayahCount: 30, isMeccan: true),
  SurahInfo(number: 33, nameArabic: 'الأحزاب', nameTranslit: 'Al-Ahzab', nameRussian: 'Сонмы', nameEnglish: 'The Combined Forces', ayahCount: 73, isMeccan: false),
  SurahInfo(number: 34, nameArabic: 'سبأ', nameTranslit: 'Saba', nameRussian: 'Саба', nameEnglish: 'Sheba', ayahCount: 54, isMeccan: true),
  SurahInfo(number: 35, nameArabic: 'فاطر', nameTranslit: 'Fatir', nameRussian: 'Творец', nameEnglish: 'Originator', ayahCount: 45, isMeccan: true),
  SurahInfo(number: 36, nameArabic: 'يس', nameTranslit: 'Ya-Sin', nameRussian: 'Йа Син', nameEnglish: 'Ya-Sin', ayahCount: 83, isMeccan: true),
  SurahInfo(number: 37, nameArabic: 'الصافات', nameTranslit: 'As-Saffat', nameRussian: 'Выстроившиеся в ряды', nameEnglish: 'Those who set the Ranks', ayahCount: 182, isMeccan: true),
  SurahInfo(number: 38, nameArabic: 'ص', nameTranslit: 'Sad', nameRussian: 'Сад', nameEnglish: 'The Letter Sad', ayahCount: 88, isMeccan: true),
  SurahInfo(number: 39, nameArabic: 'الزمر', nameTranslit: 'Az-Zumar', nameRussian: 'Толпы', nameEnglish: 'The Troops', ayahCount: 75, isMeccan: true),
  SurahInfo(number: 40, nameArabic: 'غافر', nameTranslit: 'Ghafir', nameRussian: 'Прощающий', nameEnglish: 'The Forgiver', ayahCount: 85, isMeccan: true),
  SurahInfo(number: 41, nameArabic: 'فصلت', nameTranslit: 'Fussilat', nameRussian: 'Разъяснены', nameEnglish: 'Explained in Detail', ayahCount: 54, isMeccan: true),
  SurahInfo(number: 42, nameArabic: 'الشورى', nameTranslit: 'Ash-Shura', nameRussian: 'Совет', nameEnglish: 'The Consultation', ayahCount: 53, isMeccan: true),
  SurahInfo(number: 43, nameArabic: 'الزخرف', nameTranslit: 'Az-Zukhruf', nameRussian: 'Украшения', nameEnglish: 'The Gold Adornments', ayahCount: 89, isMeccan: true),
  SurahInfo(number: 44, nameArabic: 'الدخان', nameTranslit: 'Ad-Dukhan', nameRussian: 'Дым', nameEnglish: 'The Smoke', ayahCount: 59, isMeccan: true),
  SurahInfo(number: 45, nameArabic: 'الجاثية', nameTranslit: 'Al-Jathiyah', nameRussian: 'Коленопреклонённые', nameEnglish: 'The Crouching', ayahCount: 37, isMeccan: true),
  SurahInfo(number: 46, nameArabic: 'الأحقاف', nameTranslit: 'Al-Ahqaf', nameRussian: 'Барханы', nameEnglish: 'The Wind-Curved Sandhills', ayahCount: 35, isMeccan: true),
  SurahInfo(number: 47, nameArabic: 'محمد', nameTranslit: 'Muhammad', nameRussian: 'Мухаммад', nameEnglish: 'Muhammad', ayahCount: 38, isMeccan: false),
  SurahInfo(number: 48, nameArabic: 'الفتح', nameTranslit: 'Al-Fath', nameRussian: 'Победа', nameEnglish: 'The Victory', ayahCount: 29, isMeccan: false),
  SurahInfo(number: 49, nameArabic: 'الحجرات', nameTranslit: 'Al-Hujurat', nameRussian: 'Комнаты', nameEnglish: 'The Rooms', ayahCount: 18, isMeccan: false),
  SurahInfo(number: 50, nameArabic: 'ق', nameTranslit: 'Qaf', nameRussian: 'Каф', nameEnglish: 'The Letter Qaf', ayahCount: 45, isMeccan: true),
  SurahInfo(number: 51, nameArabic: 'الذاريات', nameTranslit: 'Adh-Dhariyat', nameRussian: 'Рассеивающие', nameEnglish: 'The Winnowing Winds', ayahCount: 60, isMeccan: true),
  SurahInfo(number: 52, nameArabic: 'الطور', nameTranslit: 'At-Tur', nameRussian: 'Гора', nameEnglish: 'The Mount', ayahCount: 49, isMeccan: true),
  SurahInfo(number: 53, nameArabic: 'النجم', nameTranslit: 'An-Najm', nameRussian: 'Звезда', nameEnglish: 'The Star', ayahCount: 62, isMeccan: true),
  SurahInfo(number: 54, nameArabic: 'القمر', nameTranslit: 'Al-Qamar', nameRussian: 'Луна', nameEnglish: 'The Moon', ayahCount: 55, isMeccan: true),
  SurahInfo(number: 55, nameArabic: 'الرحمن', nameTranslit: 'Ar-Rahman', nameRussian: 'Милостивый', nameEnglish: 'The Beneficent', ayahCount: 78, isMeccan: false),
  SurahInfo(number: 56, nameArabic: 'الواقعة', nameTranslit: 'Al-Waqiah', nameRussian: 'Событие', nameEnglish: 'The Inevitable', ayahCount: 96, isMeccan: true),
  SurahInfo(number: 57, nameArabic: 'الحديد', nameTranslit: 'Al-Hadid', nameRussian: 'Железо', nameEnglish: 'The Iron', ayahCount: 29, isMeccan: false),
  SurahInfo(number: 58, nameArabic: 'المجادلة', nameTranslit: 'Al-Mujadilah', nameRussian: 'Препирающаяся', nameEnglish: 'The Pleading Woman', ayahCount: 22, isMeccan: false),
  SurahInfo(number: 59, nameArabic: 'الحشر', nameTranslit: 'Al-Hashr', nameRussian: 'Собрание', nameEnglish: 'The Exile', ayahCount: 24, isMeccan: false),
  SurahInfo(number: 60, nameArabic: 'الممتحنة', nameTranslit: 'Al-Mumtahanah', nameRussian: 'Испытуемая', nameEnglish: 'The Examined One', ayahCount: 13, isMeccan: false),
  SurahInfo(number: 61, nameArabic: 'الصف', nameTranslit: 'As-Saff', nameRussian: 'Ряды', nameEnglish: 'The Ranks', ayahCount: 14, isMeccan: false),
  SurahInfo(number: 62, nameArabic: 'الجمعة', nameTranslit: 'Al-Jumuah', nameRussian: 'Пятница', nameEnglish: 'The Congregation', ayahCount: 11, isMeccan: false),
  SurahInfo(number: 63, nameArabic: 'المنافقون', nameTranslit: 'Al-Munafiqun', nameRussian: 'Лицемеры', nameEnglish: 'The Hypocrites', ayahCount: 11, isMeccan: false),
  SurahInfo(number: 64, nameArabic: 'التغابن', nameTranslit: 'At-Taghabun', nameRussian: 'Взаимное обделение', nameEnglish: 'The Mutual Disillusion', ayahCount: 18, isMeccan: false),
  SurahInfo(number: 65, nameArabic: 'الطلاق', nameTranslit: 'At-Talaq', nameRussian: 'Развод', nameEnglish: 'The Divorce', ayahCount: 12, isMeccan: false),
  SurahInfo(number: 66, nameArabic: 'التحريم', nameTranslit: 'At-Tahrim', nameRussian: 'Запрещение', nameEnglish: 'The Prohibition', ayahCount: 12, isMeccan: false),
  SurahInfo(number: 67, nameArabic: 'الملك', nameTranslit: 'Al-Mulk', nameRussian: 'Власть', nameEnglish: 'The Sovereignty', ayahCount: 30, isMeccan: true),
  SurahInfo(number: 68, nameArabic: 'القلم', nameTranslit: 'Al-Qalam', nameRussian: 'Тростниковое перо', nameEnglish: 'The Pen', ayahCount: 52, isMeccan: true),
  SurahInfo(number: 69, nameArabic: 'الحاقة', nameTranslit: 'Al-Haqqah', nameRussian: 'Неминуемое', nameEnglish: 'The Reality', ayahCount: 52, isMeccan: true),
  SurahInfo(number: 70, nameArabic: 'المعارج', nameTranslit: 'Al-Maarij', nameRussian: 'Ступени', nameEnglish: 'The Ascending Stairways', ayahCount: 44, isMeccan: true),
  SurahInfo(number: 71, nameArabic: 'نوح', nameTranslit: 'Nuh', nameRussian: 'Нух', nameEnglish: 'Noah', ayahCount: 28, isMeccan: true),
  SurahInfo(number: 72, nameArabic: 'الجن', nameTranslit: 'Al-Jinn', nameRussian: 'Джинны', nameEnglish: 'The Jinn', ayahCount: 28, isMeccan: true),
  SurahInfo(number: 73, nameArabic: 'المزمل', nameTranslit: 'Al-Muzzammil', nameRussian: 'Закутавшийся', nameEnglish: 'The Enshrouded One', ayahCount: 20, isMeccan: true),
  SurahInfo(number: 74, nameArabic: 'المدثر', nameTranslit: 'Al-Muddaththir', nameRussian: 'Завернувшийся', nameEnglish: 'The Cloaked One', ayahCount: 56, isMeccan: true),
  SurahInfo(number: 75, nameArabic: 'القيامة', nameTranslit: 'Al-Qiyamah', nameRussian: 'Воскресение', nameEnglish: 'The Resurrection', ayahCount: 40, isMeccan: true),
  SurahInfo(number: 76, nameArabic: 'الإنسان', nameTranslit: 'Al-Insan', nameRussian: 'Человек', nameEnglish: 'The Man', ayahCount: 31, isMeccan: false),
  SurahInfo(number: 77, nameArabic: 'المرسلات', nameTranslit: 'Al-Mursalat', nameRussian: 'Посылаемые', nameEnglish: 'The Emissaries', ayahCount: 50, isMeccan: true),
  SurahInfo(number: 78, nameArabic: 'النبأ', nameTranslit: 'An-Naba', nameRussian: 'Весть', nameEnglish: 'The Tidings', ayahCount: 40, isMeccan: true),
  SurahInfo(number: 79, nameArabic: 'النازعات', nameTranslit: 'An-Naziat', nameRussian: 'Исторгающие', nameEnglish: 'Those Who Drag Forth', ayahCount: 46, isMeccan: true),
  SurahInfo(number: 80, nameArabic: 'عبس', nameTranslit: 'Abasa', nameRussian: 'Нахмурился', nameEnglish: 'He Frowned', ayahCount: 42, isMeccan: true),
  SurahInfo(number: 81, nameArabic: 'التكوير', nameTranslit: 'At-Takwir', nameRussian: 'Скручивание', nameEnglish: 'The Overthrowing', ayahCount: 29, isMeccan: true),
  SurahInfo(number: 82, nameArabic: 'الانفطار', nameTranslit: 'Al-Infitar', nameRussian: 'Раскалывание', nameEnglish: 'The Cleaving', ayahCount: 19, isMeccan: true),
  SurahInfo(number: 83, nameArabic: 'المطففين', nameTranslit: 'Al-Mutaffifin', nameRussian: 'Обвешивающие', nameEnglish: 'The Defrauding', ayahCount: 36, isMeccan: true),
  SurahInfo(number: 84, nameArabic: 'الانشقاق', nameTranslit: 'Al-Inshiqaq', nameRussian: 'Разверзнется', nameEnglish: 'The Splitting Open', ayahCount: 25, isMeccan: true),
  SurahInfo(number: 85, nameArabic: 'البروج', nameTranslit: 'Al-Buruj', nameRussian: 'Созвездия зодиака', nameEnglish: 'The Mansions of the Stars', ayahCount: 22, isMeccan: true),
  SurahInfo(number: 86, nameArabic: 'الطارق', nameTranslit: 'At-Tariq', nameRussian: 'Ночной путник', nameEnglish: 'The Morning Star', ayahCount: 17, isMeccan: true),
  SurahInfo(number: 87, nameArabic: 'الأعلى', nameTranslit: 'Al-Ala', nameRussian: 'Всевышний', nameEnglish: 'The Most High', ayahCount: 19, isMeccan: true),
  SurahInfo(number: 88, nameArabic: 'الغاشية', nameTranslit: 'Al-Ghashiyah', nameRussian: 'Покрывающее', nameEnglish: 'The Overwhelming', ayahCount: 26, isMeccan: true),
  SurahInfo(number: 89, nameArabic: 'الفجر', nameTranslit: 'Al-Fajr', nameRussian: 'Заря', nameEnglish: 'The Dawn', ayahCount: 30, isMeccan: true),
  SurahInfo(number: 90, nameArabic: 'البلد', nameTranslit: 'Al-Balad', nameRussian: 'Город', nameEnglish: 'The City', ayahCount: 20, isMeccan: true),
  SurahInfo(number: 91, nameArabic: 'الشمس', nameTranslit: 'Ash-Shams', nameRussian: 'Солнце', nameEnglish: 'The Sun', ayahCount: 15, isMeccan: true),
  SurahInfo(number: 92, nameArabic: 'الليل', nameTranslit: 'Al-Layl', nameRussian: 'Ночь', nameEnglish: 'The Night', ayahCount: 21, isMeccan: true),
  SurahInfo(number: 93, nameArabic: 'الضحى', nameTranslit: 'Ad-Duha', nameRussian: 'Утро', nameEnglish: 'The Morning Hours', ayahCount: 11, isMeccan: true),
  SurahInfo(number: 94, nameArabic: 'الشرح', nameTranslit: 'Ash-Sharh', nameRussian: 'Раскрытие', nameEnglish: 'The Relief', ayahCount: 8, isMeccan: true),
  SurahInfo(number: 95, nameArabic: 'التين', nameTranslit: 'At-Tin', nameRussian: 'Смоковница', nameEnglish: 'The Fig', ayahCount: 8, isMeccan: true),
  SurahInfo(number: 96, nameArabic: 'العلق', nameTranslit: 'Al-Alaq', nameRussian: 'Сгусток крови', nameEnglish: 'The Clot', ayahCount: 19, isMeccan: true),
  SurahInfo(number: 97, nameArabic: 'القدر', nameTranslit: 'Al-Qadr', nameRussian: 'Предопределение', nameEnglish: 'The Power', ayahCount: 5, isMeccan: true),
  SurahInfo(number: 98, nameArabic: 'البينة', nameTranslit: 'Al-Bayyinah', nameRussian: 'Ясное знамение', nameEnglish: 'The Clear Proof', ayahCount: 8, isMeccan: false),
  SurahInfo(number: 99, nameArabic: 'الزلزلة', nameTranslit: 'Az-Zalzalah', nameRussian: 'Сотрясение', nameEnglish: 'The Earthquake', ayahCount: 8, isMeccan: false),
  SurahInfo(number: 100, nameArabic: 'العاديات', nameTranslit: 'Al-Adiyat', nameRussian: 'Скачущие', nameEnglish: 'The Courser', ayahCount: 11, isMeccan: true),
  SurahInfo(number: 101, nameArabic: 'القارعة', nameTranslit: 'Al-Qariah', nameRussian: 'Великое бедствие', nameEnglish: 'The Calamity', ayahCount: 11, isMeccan: true),
  SurahInfo(number: 102, nameArabic: 'التكاثر', nameTranslit: 'At-Takathur', nameRussian: 'Страсть к приумножению', nameEnglish: 'The Rivalry in World Increase', ayahCount: 8, isMeccan: true),
  SurahInfo(number: 103, nameArabic: 'العصر', nameTranslit: 'Al-Asr', nameRussian: 'Предвечернее время', nameEnglish: 'The Declining Day', ayahCount: 3, isMeccan: true),
  SurahInfo(number: 104, nameArabic: 'الهمزة', nameTranslit: 'Al-Humazah', nameRussian: 'Хулитель', nameEnglish: 'The Traducer', ayahCount: 9, isMeccan: true),
  SurahInfo(number: 105, nameArabic: 'الفيل', nameTranslit: 'Al-Fil', nameRussian: 'Слон', nameEnglish: 'The Elephant', ayahCount: 5, isMeccan: true),
  SurahInfo(number: 106, nameArabic: 'قريش', nameTranslit: 'Quraysh', nameRussian: 'Курайшиты', nameEnglish: 'Quraysh', ayahCount: 4, isMeccan: true),
  SurahInfo(number: 107, nameArabic: 'الماعون', nameTranslit: 'Al-Maun', nameRussian: 'Утварь', nameEnglish: 'The Small Kindnesses', ayahCount: 7, isMeccan: true),
  SurahInfo(number: 108, nameArabic: 'الكوثر', nameTranslit: 'Al-Kawthar', nameRussian: 'Изобилие', nameEnglish: 'The Abundance', ayahCount: 3, isMeccan: true),
  SurahInfo(number: 109, nameArabic: 'الكافرون', nameTranslit: 'Al-Kafirun', nameRussian: 'Неверующие', nameEnglish: 'The Disbelievers', ayahCount: 6, isMeccan: true),
  SurahInfo(number: 110, nameArabic: 'النصر', nameTranslit: 'An-Nasr', nameRussian: 'Помощь', nameEnglish: 'The Divine Support', ayahCount: 3, isMeccan: false),
  SurahInfo(number: 111, nameArabic: 'المسد', nameTranslit: 'Al-Masad', nameRussian: 'Пальмовые волокна', nameEnglish: 'The Palm Fiber', ayahCount: 5, isMeccan: true),
  SurahInfo(number: 112, nameArabic: 'الإخلاص', nameTranslit: 'Al-Ikhlas', nameRussian: 'Очищение веры', nameEnglish: 'The Sincerity', ayahCount: 4, isMeccan: true),
  SurahInfo(number: 113, nameArabic: 'الفلق', nameTranslit: 'Al-Falaq', nameRussian: 'Рассвет', nameEnglish: 'The Daybreak', ayahCount: 5, isMeccan: true),
  SurahInfo(number: 114, nameArabic: 'الناس', nameTranslit: 'An-Nas', nameRussian: 'Люди', nameEnglish: 'The Mankind', ayahCount: 6, isMeccan: true),
];

SurahInfo getSurah(int number) => kSurahs[number - 1];
